### ISSUE TITLE
Why .md files

### ISSUE THREAD

**Issue by karneaud** [petermorlion/RedStarITSite#1]
Hello,

I'm new to using metalsmith and was wondering why do they use *.md files? can this be substituted?

**Comment by petermorlion** [comment]
*.md files are [Markdown files](http://daringfireball.net/projects/markdown/). It allows for an easy way to write readable content that can be transformed to html. Html is the format of the web, but requires a lot of verbose tags, whereas in Markdown, your content is central. You can much easier and more quickly see what the contents of a document is.

I'm pretty sure you could set up Metalsmith without Markdown, but I find it a very easy format. Question is, with what would you want to substitute it? As the markdown files get converted to JS objects, you could very likely use JSON files too.
